export const metadata = {
    author: '鸢离',
    siteUrl:'www.imyuanli.cn',
    description:'这里是鸢离的网站首页,包含了我的部分作品及个人博客',
    title: 'YuanLi\'s Index',
    email: '2865437316@qq.com',
    github: 'https://github.com/imyuanli',
    gitee: 'https://gitee.com/imyuanli',
    csdn: 'https://blog.csdn.net/qq_44259670',
    qq: '2865437316',
    primaryColor:'#14B8A6',
    serverURL:'https://waline.imyuanli.cn'
}

export const DEFAULT_WORK_LIST = [
    {
        name: 'aTools',
        link: 'https://atools.imyuanli.cn',
        description: '在线的免费工具，开箱即用',
        tag: '在线网页',
        version: '1.8.6',
        logo: '',
        status: 1,
    },
    {
        name: 'mini起始页',
        link: 'https://mini.imyuanli.cn',
        description: '简洁、美观、实用的浏览器起始页',
        tag: '在线网页',
        version: '1.1.4',
        logo: '/mini.png',
        status: 1,
    },
    {
        name: '简历制作',
        link: 'https://resume.imyuanli.cn/',
        description: '简单快速的制作你的简历',
        tag: '在线网页',
        version: '1.1.0',
        logo: '',
        status: 1,
    },
    {
        name: 'yuanli博客',
        link: 'https://blog.imyuanli.cn',
        description: '自己的博客，记录一些相关技术和有趣的事',
        tag: '在线网页',
        version: '1.0.0',
        logo: '',
        status: 1,
    },
    {
        name: '生成readme',
        link: 'https://readme.imyuanli.cn',
        description: '更加方便的制作你的Github README.md',
        tag: '在线网页',
        version: '1.1.8',
        logo: '',
        status: 1,
    },
    // // {
    // //     name: 'oneLink',
    // //     link:'https://onelink.imyuanli.cn',
    // //     description: '一键生成你的个人主页',
    // //     tag: '在线网页',
    // //     version:'0.0.0',
    // //     logo:'',
    // //     status:0,
    // // },
    // // {
    // //     name: 'done',
    // //     link:'https://done.imyuanli.cn',
    // //     description: '高效的团队协作工具',
    // //     tag: '在线网页',
    // //     version:'0.0.0',
    // //     logo:'',
    // //     status:0,
    // // },
    // // {
    // //     name: 'mi',
    // //     link:'https://mi.imyuanli.cn',
    // //     description: '融合精准的',
    // //     tag: '在线网页',
    // //     version:'0.0.0',
    // //     logo:'',
    // //     status:0,
    // // },
]


export const test_article = [
    {
        id:1231,
        title:'测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦',
        content:'测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦',
        tag:'Javascript',
        createAt:'2022/01/04',
        updateAt:'2022/01/04',
        viewCount:123123,
        commentCount:123123,
        isDelete:0,   //0未删除 ,  1删除
    },
    {
        id:1231231,
        title:'阿飞噶沙发上阿飞噶沙发上',
        content:'测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦测试机十四hi哈撒旦撒旦',
        tag:'Javascript',
        createAt:'2022/01/04',
        updateAt:'2022/01/04',
        viewCount:123123,
        commentCount:123123,
        isDelete:0,   //0未删除 ,  1删除
    },
    {
        id:1241312331,
        title:'阿斯蒂芬',
        content:'阿斯蒂芬阿斯蒂芬阿斯蒂芬阿斯蒂芬阿松大',
        tag:'Javascript',
        createAt:'2022/01/04',
        updateAt:'2022/01/04',
        viewCount:123123,
        commentCount:123123,
        isDelete:0,   //0未删除 ,  1删除
    },
    {
        id:1241331,
        title:'阿斯蒂芬',
        content:'阿斯蒂芬阿斯蒂芬阿斯蒂芬阿斯蒂芬阿松大',
        tag:'Javascript',
        createAt:'2022/01/04',
        updateAt:'2022/01/04',
        viewCount:123123,
        commentCount:123123,
        isDelete:0,   //0未删除 ,  1删除
    },
    {
        id:124131331,
        title:'阿斯蒂芬',
        content:'阿斯蒂芬阿斯蒂芬阿斯蒂芬阿斯蒂芬阿松大',
        tag:'Javascript',
        createAt:'2022/01/04',
        updateAt:'2022/01/04',
        viewCount:123123,
        commentCount:123123,
        isDelete:0,   //0未删除 ,  1删除
    },
    {
        id:12413136631,
        title:'addasd1231 fasfa的大事',
        content:'阿斯蒂芬阿斯蒂芬阿asd 斯蒂芬阿斯蒂芬阿松大阿斯蒂芬阿斯蒂芬阿斯蒂芬阿斯蒂芬阿松大addasd',
        tag:'Javascript',
        createAt:'2022/01/04',
        updateAt:'2022/01/04',
        viewCount:123123,
        commentCount:123123,
        isDelete:0,   //0未删除 ,  1删除
    },
]