import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {Anchor, Button, Card, Divider, Tag, Timeline} from "antd";
import {useEffect, useState} from "react";
import Image from 'next/image'
import Logo from '../public/logo.png'
import bgImg from '../public/infinity-3640497.jpg'
import {ClockCircleOutlined, DownOutlined} from "@ant-design/icons";
import {DEFAULT_WORK_LIST} from "@/utils";
import Title from "@/components/title";

const {Meta} = Card;
export default function Home() {
    const [visible, setVisible] = useState(false)
    useEffect(() => {
        handleScroll()
    }, [])

    const handleScroll = () => {
        window.addEventListener('scroll', () => {
            if (document.documentElement.scrollTop > 80) {
                setVisible(true)
            } else {
                setVisible(false)
            }
        })
    }

    const getBtn = (text: string) => (
        <Button className={`${visible ? 'text-black' : 'text-white'}`} type="text" size={'large'}>{text}</Button>
    )

    const sectionClass = 'py-24 flex-center flex-col px-12'
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={'min-h-screen w-full text-lg relative overflow-hidden'}>
                <header className={`${visible ? 'fixed bg-white shadow-lg' : 'absolute'} w-full z-10 flex-center h-20`}>
                    <div className={`${styles.headerContent} flex justify-between`}>
                        <div className={'flex-center'}>
                            <Image
                                src={Logo}
                                alt="YuanLi"
                                width={60}
                            />
                        </div>
                        <Anchor
                            direction="horizontal"
                            items={[
                                {
                                    key: 'home',
                                    href: '#home',
                                    title: getBtn('首页'),
                                },
                                {
                                    key: 'about',
                                    href: '#about',
                                    title: getBtn('关于'),
                                },
                                {
                                    key: 'work',
                                    href: '#work',
                                    title: getBtn('作品'),
                                },
                                {
                                    key: 'log',
                                    href: '#log',
                                    title: getBtn('日志'),
                                },
                            ]}
                            className={'text-white'}
                        />
                    </div>
                </header>
                <Image
                    src={bgImg}
                    alt={'背景'}
                    className={'fixed min-h-screen -z-10 object-cover'}
                />
                <section
                    id={'home'}
                    className={styles.home}
                >
                    <div
                        className={'absolute left-1/2 top-1/3 -translate-x-1/2 flex-center flex-col text-white w-full'}>
                        不积跬步，无以至千里。
                    </div>
                    <div className={'absolute bottom-9 left-1/2 -translate-x-1/2'}>
                        <Anchor
                            items={[
                                {
                                    key: 'about',
                                    href: '#about',
                                    title: <DownOutlined className={'text-gray-400 text-3xl'}/>,
                                },
                            ]}
                        />
                    </div>
                </section>
                <section id={'about'} className={`bg-white ${sectionClass}`}>
                    <Title text={'关于我'}/>
                    <div className={'mb-3'}>
                        <Tag>00后</Tag>
                        <Tag>一个前端开发</Tag>
                        <Tag>会点后端</Tag>
                        <Tag>00后</Tag>
                    </div>
                    <div className={'flex-center flex-col'}>
                        <p>123</p>
                        <p>123</p>
                        <p>123123123123123123123123123123</p>
                        <p>12312312313123123123</p>
                        <p>1123123123123123123123123</p>
                        <p>123</p>
                        <p>123</p>
                        <p>123</p>
                        <p>123</p>
                        <p>123</p>
                        <p>123</p>
                        <p>123</p>
                    </div>
                </section>
                <section id={'work'} className={`bg-gray-100 ${sectionClass}`}>
                    <Title text={'我的作品'}/>
                    <div className={'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4'}>
                        {
                            DEFAULT_WORK_LIST.map((item, index) => {
                                return (
                                    <div key={index}>
                                        <Card
                                            hoverable={true}
                                            style={{
                                                maxWidth: 300,
                                            }}
                                            cover={
                                                <Image
                                                    alt="example"
                                                    src={bgImg}
                                                />
                                            }
                                        >
                                            <Meta
                                                title={item.name}
                                                description={item.description}
                                            />
                                        </Card>
                                    </div>
                                )
                            })
                        }
                    </div>
                </section>
                <section id={'log'} className={`bg-white ${sectionClass}`}>
                    <Title text={'网站日志'}/>
                    <div>
                        <Timeline
                            mode="alternate"
                            items={[
                                {
                                    children: 'Create a services site 2015-09-01',
                                },
                                {
                                    children: 'Solve initial network problems 2015-09-01',
                                    color: 'green',
                                },
                                {
                                    dot: <ClockCircleOutlined style={{ fontSize: '16px' }} />,
                                    children: `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.`,
                                },
                                {
                                    color: 'red',
                                    children: 'Network problems being solved 2015-09-01',
                                },
                                {
                                    children: 'Create a services site 2015-09-01',
                                },
                                {
                                    dot: <ClockCircleOutlined style={{ fontSize: '16px' }} />,
                                    children: 'Technical testing 2015-09-01',
                                },
                            ]}
                        />
                    </div>
                </section>
                <footer>
                    <div className={'text-white flex-center'}>© {new Date().getFullYear()} 鸢离</div>
                </footer>
            </main>
        </>
    )
}
