import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {Anchor, Button} from "antd";
import Image from 'next/image'
import Logo from '../public/logo.png'

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={'min-h-screen w-full text-lg'}>
                <div
                    id={'home'}
                    className={'min-h-screen'}
                >
                    <div className={'w-full flex-center h-20'}>
                        <div className={`${styles.headerContent} flex justify-between`}>
                            <div className={'flex-center'}>
                                <Image
                                    src={Logo}
                                    alt="YuanLi"
                                    width={60}
                                />
                            </div>
                            <Anchor
                                direction="horizontal"
                                affix={false}
                                items={[
                                    {
                                        key: 'home',
                                        href: '#home',
                                        title: <Button type="text" size={'large'}>首页</Button>,
                                    },
                                    {
                                        key: 'about',
                                        href: '#about',
                                        title: <Button type="text" size={'large'}>关于</Button>,
                                    },
                                    {
                                        key: 'work',
                                        href: '#work',
                                        title: <Button type="text" size={'large'}>作品</Button>,
                                    },
                                    {
                                        key: 'log',
                                        href: '#log',
                                        title: <Button type="text" size={'large'}>日志</Button>,
                                    },
                                ]}
                            />
                        </div>
                    </div>
                    <div className={''}>
                        <div>
                            设计 1 + 2，摹客就够了！
                        </div>
                        <div>
                            立即开始
                        </div>
                    </div>
                </div>
                <div id={'about'} className={'min-h-screen bg-amber-600'}>
                    about
                </div>
                <div id={'work'} className={'min-h-screen bg-amber-600'}>
                    work
                </div>
                <div id={'log'} className={'min-h-screen bg-amber-600'}>
                    log
                </div>
            </main>
        </>
    )
}
